### ISSUE TITLE
Mobile app: fix error while playing twice at the same position

### ISSUE THREAD

**Issue by slax57** [marmelab/Hex#48]
Mobile app currently allows to play twice at the same position, resulting in an error since the API won't allow it.

Stacktrace:

```
Board.tsx:19 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Board (Board.tsx:19:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22779:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at dispatchAction (react-dom.development.js:16139:1)
```

We should
- Make the non-empty cells non-clickable
- Have better handling of API errors

**Comment by slax57** [comment]
Non-empty cells are no longer clickable 🙂
